// Original grammatika testlari — A1, A2, B1, B2 darajalari uchun, har birida 40 tadan savol.
// Har bir savol: { q: "gap bo'sh joy bilan", options: [4 ta variant], correct: to'g'ri variant indeksi (0-3) }

const A1 = [
  { q: "Ben öğrenci____.", options: ["-yim", "-sin", "-dir", "-ler"], correct: 0 },
  { q: "Sen çok çalışkan____.", options: ["-sın", "-yim", "-dır", "-ız"], correct: 0 },
  { q: "O bir doktor____.", options: ["-dur", "-yim", "-sin", "-ız"], correct: 0 },
  { q: "Biz Özbek____.", options: ["-iz", "-sin", "-dir", "-ler"], correct: 0 },
  { q: "Onlar öğretmen____.", options: ["-ler", "-yim", "-sin", "-iz"], correct: 0 },
  { q: "Kitap masanın üzeri____.", options: ["-nde", "-den", "-e", "-i"], correct: 0 },
  { q: "Ben eve gidiyor____.", options: ["-um", "-sun", "-lar", "-uz"], correct: 0 },
  { q: "Sen ne yapıyor____?", options: ["-sun", "-um", "-lar", "-uz"], correct: 0 },
  { q: "Bu bir kalem____?", options: ["mi", "mı", "mu", "mü"], correct: 0 },
  { q: "Masada kitap var____?", options: ["mı", "mi", "mu", "mü"], correct: 0 },
  { q: "Cüzdanda para yok____?", options: ["mu", "mı", "mi", "mü"], correct: 0 },
  { q: "Ben ve kardeşim ev____ gidiyoruz.", options: ["-e", "-de", "-den", "-i"], correct: 0 },
  { q: "Okul____ geliyorum.", options: ["-dan", "-a", "-da", "-ı"], correct: 0 },
  { q: "Bu benim kitab____.", options: ["-ım", "-in", "-i", "-imiz"], correct: 0 },
  { q: "Senin ev____ nerede?", options: ["-in", "-im", "-i", "-imiz"], correct: 0 },
  { q: "Masada____ kitap var. (5)", options: ["beş", "beşinci", "beşler", "beşim"], correct: 0 },
  { q: "Bu ev çok büyük____.", options: ["-tür", "-yim", "-sin", "-iz"], correct: 0 },
  { q: "Bugün hava soğuk____.", options: ["-tur", "-yim", "-sin", "-ız"], correct: 0 },
  { q: "Ben yorgun____, dinlenmek istiyorum.", options: ["-um", "-sun", "-dur", "-uz"], correct: 0 },
  { q: "Siz Türkçe biliyor____?", options: ["musunuz", "musun", "mısınız", "misiniz"], correct: 0 },
  { q: "Ben şimdi kahve iç____.", options: ["miyorum", "yorum", "tim", "eceğim"], correct: 0 },
  { q: "Sen de bize geliyor____?", options: ["musun", "mısın", "musunuz", "misin"], correct: 0 },
  { q: "____ benim evim, şu senin evin.", options: ["Bu", "Şu", "O", "Onlar"], correct: 0 },
  { q: "Masada hiç elma____.", options: ["yok", "var", "değil", "değildir"], correct: 0 },
  { q: "Ben bugün çok mutlu____, çünkü tatilim başladı.", options: ["yum", "sun", "dur", "uz"], correct: 0 },
  { q: "Siz yarın bize gel____ misiniz?", options: ["ecek", "di", "iyor", "ir"], correct: 0 },
  { q: "O, kitabı masa____ koydu.", options: ["nın üzerine", "nın üzerinde", "dan", "a"], correct: 0 },
  { q: "Ben ve sen yarın buluş____.", options: ["acağız", "tuk", "uyoruz", "ur"], correct: 0 },
  { q: "Bu kalem kim____?", options: ["in", "e", "i", "den"], correct: 0 },
  { q: "Ben film izlemeyi çok sev____.", options: ["erim", "dim", "eceğim", "iyorum"], correct: 0 },
  { q: "Yarın hava nasıl ol____?", options: ["acak", "du", "uyor", "ur"], correct: 0 },
  { q: "Ali ile Ayşe sinema____ gidiyorlar.", options: ["ya", "dan", "da", "nın"], correct: 0 },
  { q: "Ben her gün saat yedi____ kalkarım.", options: ["de", "den", "e", "i"], correct: 0 },
  { q: "Bu araba çok pahalı,____ o araba ucuz.", options: ["ama", "için", "çünkü", "ki"], correct: 0 },
  { q: "Ben____ kardeşim İstanbul'da yaşıyoruz.", options: ["ve", "ama", "veya", "ki"], correct: 0 },
  { q: "O, hafta sonu genellikle ne yap____?", options: ["ar", "tı", "acak", "ıyor"], correct: 0 },
  { q: "Sen benim en iyi arkadaş____.", options: ["ımsın", "ım", "ısın", "ları"], correct: 0 },
  { q: "Bu çiçekler çok güzel koku____.", options: ["yor", "du", "acak", "muş"], correct: 0 },
  { q: "Ben yarın değil, bugün gel____.", options: ["iyorum", "dim", "eceğim", "irim"], correct: 0 },
  { q: "Biz____ üç kişiyiz: annem, babam ve ben.", options: ["evde", "eve", "evden", "evi"], correct: 0 },
];

const A2 = [
  { q: "Dün ben okula____.", options: ["gittim", "gideceğim", "gidiyorum", "giderim"], correct: 0 },
  { q: "Yarın biz sinemaya____.", options: ["gideceğiz", "gittik", "gidiyoruz", "giderdik"], correct: 0 },
  { q: "Lütfen kapıyı____!", options: ["kapat", "kapatıyor", "kapattı", "kapatacak"], correct: 0 },
  { q: "Bu kitap o kitaptan____ ilginç.", options: ["daha", "en", "çok", "gibi"], correct: 0 },
  { q: "Ben Türkçe konuş____.", options: ["abilirim", "iyorum", "tum", "acağım"], correct: 0 },
  { q: "Ben spor yapmak____ parka gidiyorum.", options: ["için", "ama", "çünkü", "gibi"], correct: 0 },
  { q: "Param yok,____ pazara gidemem.", options: ["bu yüzden", "ama", "ve", "gibi"], correct: 0 },
  { q: "Hava güzel____ soğuk.", options: ["ama", "çünkü", "için", "ki"], correct: 0 },
  { q: "Ben yarın erken kalkmam____.", options: ["gerekiyor", "gerekiyorum", "gerekli", "gerek"], correct: 0 },
  { q: "O, bu akşam bize gel____ istiyor.", options: ["mek", "meye", "erek", "diği"], correct: 0 },
  { q: "Biz geçen yıl İstanbul'a____.", options: ["gittik", "gideceğiz", "gidiyoruz", "gitmiştik"], correct: 0 },
  { q: "Sen dün akşam ne____?", options: ["yaptın", "yapacaksın", "yapıyorsun", "yapardın"], correct: 0 },
  { q: "Ali her sabah erken____.", options: ["kalkar", "kalktı", "kalkacak", "kalkıyor"], correct: 0 },
  { q: "Ben bu filmi daha önce____.", options: ["izlemedim", "izlemeyeceğim", "izlemiyorum", "izlemem"], correct: 0 },
  { q: "Lütfen bana yardım____!", options: ["et", "ediyor", "etti", "edecek"], correct: 0 },
  { q: "Biz yarın toplantıya katıl____.", options: ["acağız", "dık", "ıyoruz", "ır"], correct: 0 },
  { q: "Sen İngilizce____ musun?", options: ["biliyor", "bildin", "bilecek", "bilir"], correct: 0 },
  { q: "Ben bu sabah kahvaltı____.", options: ["yapmadım", "yapmayacağım", "yapmıyorum", "yapmam"], correct: 0 },
  { q: "O çok yorgun,____ erken yattı.", options: ["bu yüzden", "ama", "ve", "için"], correct: 0 },
  { q: "Biz her gün Türkçe____.", options: ["çalışırız", "çalıştık", "çalışacağız", "çalışıyoruz"], correct: 0 },
  { q: "Ben hiç sinemaya git____.", options: ["mem", "medim", "miyorum", "meyeceğim"], correct: 0 },
  { q: "O, bazen bizi____.", options: ["ziyaret eder", "ziyaret ediyor", "ziyaret etti", "ziyaret edecek"], correct: 0 },
  { q: "Ben asla yalan söyle____.", options: ["mem", "medim", "miyorum", "meyeceğim"], correct: 0 },
  { q: "Bu çanta o çantadan çok daha____.", options: ["ağır", "ağırdır", "ağırım", "ağırsın"], correct: 0 },
  { q: "Bu oda o oda____ büyük değil.", options: ["kadar", "gibi", "için", "ile"], correct: 0 },
  { q: "Ben kendi____ bu işi yaptım.", options: ["m", "min", "me", "mi"], correct: 0 },
  { q: "Buradan istasyona____ yürüyerek gidebilir miyim?", options: ["kadar", "gibi", "için", "ile"], correct: 0 },
  { q: "Yarın toplantıya erken gel____ lazım.", options: ["mem", "medim", "meyeceğim", "miyorum"], correct: 0 },
  { q: "Ona bu kitabı ben____.", options: ["verdim", "verdi", "verdin", "verdik"], correct: 0 },
  { q: "Annem bana yeni bir elbise____.", options: ["aldı", "aldım", "aldın", "aldık"], correct: 0 },
  { q: "Bu şehirde birçok tarihi yer____.", options: ["var", "vardır", "yok", "değil"], correct: 0 },
  { q: "O, tıpkı babası____ konuşuyor.", options: ["gibi", "kadar", "için", "ile"], correct: 0 },
  { q: "Ben bu sorunu çözmeye____.", options: ["çalışıyorum", "çalıştım", "çalışacağım", "çalışırım"], correct: 0 },
  { q: "Lütfen daha____ konuş, bebek uyuyor.", options: ["yavaş", "yavaşça", "yavaşlıkla", "yavaşlar"], correct: 0 },
  { q: "Ben sabahları genellikle koş____.", options: ["arım", "tum", "uyorum", "acağım"], correct: 0 },
  { q: "Bu proje bitmek____.", options: ["üzere", "için", "gibi", "kadar"], correct: 0 },
  { q: "O bana hiçbir şey____.", options: ["söylemedi", "söyledi", "söyleyecek", "söylüyor"], correct: 0 },
  { q: "Ben kendi arabam____ kullanıyorum.", options: ["ı", "ım", "a", "dan"], correct: 0 },
  { q: "O, işten sonra genellikle spor salonu____ gider.", options: ["na", "ndan", "nda", "nun"], correct: 0 },
  { q: "Bizim okulumuz sizin okulunuz____ daha büyük.", options: ["dan", "a", "da", "nın"], correct: 0 },
];

const B1 = [
  { q: "Bu ev geçen yıl____.", options: ["yapıldı", "yaptı", "yapacak", "yapıyor"], correct: 0 },
  { q: "Anne çocuğa yemek____.", options: ["yedirdi", "yedi", "yiyor", "yiyecek"], correct: 0 },
  { q: "Eğer yarın hava güzel ol____, pikniğe gideriz.", options: ["ursa", "du", "acak", "uyor"], correct: 0 },
  { q: "Kitap oku____ öğrenci çok başarılı.", options: ["yan", "du", "yor", "muş"], correct: 0 },
  { q: "O, müzik dinle____ ders çalışıyor.", options: ["yerek", "meden", "diği", "meli"], correct: 0 },
  { q: "Sağlıklı olmak için spor yap____.", options: ["malısın", "dın", "ıyorsun", "acaksın"], correct: 0 },
  { q: "Bu, sınıftaki____ zeki öğrenci.", options: ["en", "daha", "çok", "gibi"], correct: 0 },
  { q: "O, hasta olduğu____ okula gelmedi.", options: ["için", "ama", "ve", "gibi"], correct: 0 },
  { q: "Yemek ye____ önce ellerini yıka.", options: ["meden", "rek", "diği", "meli"], correct: 0 },
  { q: "Ders bit____ sonra eve gittik.", options: ["tikten", "meden", "erek", "diği"], correct: 0 },
  { q: "Bu kapı otomatik olarak____.", options: ["açılır", "açar", "açtı", "açacak"], correct: 0 },
  { q: "Öğretmen öğrenciye kitabı____.", options: ["okuttu", "okudu", "okuyor", "okuyacak"], correct: 0 },
  { q: "Param olsa, yeni bir araba____.", options: ["alırdım", "aldım", "alacağım", "alıyorum"], correct: 0 },
  { q: "Ali'nin dediğine göre, o yarın gel____.", options: ["ecekmiş", "di", "iyor", "irmiş"], correct: 0 },
  { q: "Bu problemi çöz____ yol arıyoruz.", options: ["mek için", "erek", "diği için", "meli"], correct: 0 },
  { q: "Çok çalış____, sınavı geçemedi.", options: ["masına rağmen", "dığı için", "erek", "meden"], correct: 0 },
  { q: "Hava soğu____, mont giydim.", options: ["duğu için", "yarak", "madan", "malı"], correct: 0 },
  { q: "Bu kitap çok öğrenci tarafından____.", options: ["okunuyor", "okuyor", "okuttu", "okur"], correct: 0 },
  { q: "Sınava gir____ önce çok çalıştım.", options: ["meden", "dikten", "erek", "meli"], correct: 0 },
  { q: "O, parası olmadığı için yeni telefon____.", options: ["alamadı", "aldı", "alacak", "alıyor"], correct: 0 },
  { q: "Bu sorun hemen çözül____.", options: ["meli", "dü", "üyor", "ecek"], correct: 0 },
  { q: "Ben bunu yap____ edemedim.", options: ["madan", "dıktan", "arak", "dığı için"], correct: 0 },
  { q: "Ne kadar çok çalışırsan, o kadar____ olursun.", options: ["başarılı", "başarı", "başarıyla", "başarısız"], correct: 0 },
  { q: "Ben onun haklı ol____ düşünüyorum.", options: ["duğunu", "acağını", "ması", "arak"], correct: 0 },
  { q: "Sen onun bu işi yap____ sanıyor musun?", options: ["abileceğini", "dığını", "ması", "arak"], correct: 0 },
  { q: "Hava aniden bozul____ olursa, geziyi iptal ederiz.", options: ["acak", "du", "uyor", "muş"], correct: 0 },
  { q: "Ben eve gel____, hemen yemek yaptım.", options: ["diğimde", "meden", "dığı için", "meli"], correct: 0 },
  { q: "O, müzik dinler____ araba kullanıyor.", options: ["ken", "erek", "diği için", "meden"], correct: 0 },
  { q: "Bu yıl geçen yıldan daha da____ geçti.", options: ["zor", "zorlukla", "zorlaştı", "zorlaşarak"], correct: 0 },
  { q: "O kapıyı aç____ dışarı çıktı.", options: ["ıp", "arak", "dığında", "meden"], correct: 0 },
  { q: "Sen burada ol____ sürece, ben rahatım.", options: ["duğun", "acağın", "ması", "arak"], correct: 0 },
  { q: "Patron, işçilerin erken çıkma____ izin vermedi.", options: ["sına", "sını", "sı", "ması"], correct: 0 },
  { q: "Bu proje, gerektiği____ zaman içinde tamamlandı.", options: ["kadar", "gibi", "için", "ile"], correct: 0 },
  { q: "O, bu ilacı su iç____ alamıyor.", options: ["meden", "dikten", "erek", "dığı için"], correct: 0 },
  { q: "Toplantı, planlandığı gibi saat onda başlamak____.", options: ["üzere", "için", "gibi", "kadar"], correct: 0 },
  { q: "O, sanki hiçbir şey ol____ davranıyor.", options: ["mamış gibi", "muş gibi", "acakmış gibi", "uyormuş gibi"], correct: 0 },
  { q: "Çocuk, korkmuş____ bana sarıldı.", options: ["casına", "arak", "dığı için", "meden"], correct: 0 },
  { q: "Bu haber duyulur duyulmaz herkes____.", options: ["şaşırdı", "şaşırıyor", "şaşıracak", "şaşırmış"], correct: 0 },
  { q: "O, param olmadığı halde bana yardım____.", options: ["etti", "ediyor", "edecek", "eder"], correct: 0 },
  { q: "Bu bilgiler, güvenilir bir kaynak____ alınmıştır.", options: ["tan", "a", "da", "nın"], correct: 0 },
];

const B2 = [
  { q: "Keşke daha çok zamanım____.", options: ["olsaydı", "oldu", "olacak", "oluyor"], correct: 0 },
  { q: "Onun ne zaman gel____ bilmiyorum.", options: ["eceğini", "diğini", "erek", "meden"], correct: 0 },
  { q: "Senin dediğin____ yaptım.", options: ["gibi", "için", "rağmen", "kadar"], correct: 0 },
  { q: "Param olmamasına____, tatile çıktım.", options: ["rağmen", "dolayı", "göre", "kadar"], correct: 0 },
  { q: "Trafik yoğunluğu____ geç kaldım.", options: ["ndan dolayı", "na rağmen", "e göre", "kadar"], correct: 0 },
  { q: "O, ne yemek pişirebiliyor____ temizlik yapabiliyor.", options: ["ne de", "hem de", "ama", "çünkü"], correct: 0 },
  { q: "Bu şirket hem yurt içinde____ yurt dışında hizmet veriyor.", options: ["hem de", "ne de", "ama", "rağmen"], correct: 0 },
  { q: "Sen çalış____, başarılı olamazsın.", options: ["madıkça", "dığı için", "erek", "meden"], correct: 0 },
  { q: "Toplantı başla____ herkes yerini aldı.", options: ["madan önce", "dıktan sonra", "dığında", "dığı için"], correct: 0 },
  { q: "Eve gel____ hemen duş aldım.", options: ["diğimde", "meden", "erek", "meli"], correct: 0 },
  { q: "Doktor, hastanın acilen ameliyat ol____ söyledi.", options: ["ması gerektiğini", "duğunu", "acağını", "urken"], correct: 0 },
  { q: "Bu bina deprem____ yıkıldı.", options: ["yüzünden", "rağmen", "göre", "kadar"], correct: 0 },
  { q: "Proje, ekip tarafından başarıyla tamamlan____.", options: ["dı", "dırdı", "ıyor", "acak"], correct: 0 },
  { q: "O, sınavı geçebilmek____ çok çalıştı.", options: ["için", "rağmen", "göre", "kadar"], correct: 0 },
  { q: "Hava kararmak____ eve dönmeliyiz.", options: ["üzereyken", "dığı için", "madan", "erek"], correct: 0 },
  { q: "Onun anlattığına____, olay çok ilginçmiş.", options: ["göre", "rağmen", "dolayı", "kadar"], correct: 0 },
  { q: "Çocuk, annesi eve gelene____ bekledi.", options: ["kadar", "göre", "rağmen", "dolayı"], correct: 0 },
  { q: "Bu haber duyul____ herkes şaşırdı.", options: ["duğunda", "madan", "arak", "malı"], correct: 0 },
  { q: "O kadar yoruldum____ hemen uyudum.", options: ["ki", "için", "rağmen", "göre"], correct: 0 },
  { q: "Bu sorunun çözül____ zaman alacak.", options: ["mesi", "müş", "erek", "meli"], correct: 0 },
  { q: "Eğer daha erken çıksaydık, uçağı kaçır____.", options: ["mazdık", "dık", "acaktık", "ıyorduk"], correct: 0 },
  { q: "Evde otur____ yerde, dışarı çıkıp yürüyüş yaptı.", options: ["acağı", "duğu", "ması", "arak"], correct: 0 },
  { q: "Yağmur yağ____ takdirde, etkinliği iptal edeceğiz.", options: ["dığı", "acağı", "ması", "arak"], correct: 0 },
  { q: "O, ne zengin____ fakirdi, orta halliydi.", options: ["ne de", "hem de", "ama", "için"], correct: 0 },
  { q: "Çocuk, sanki büyük bir başarı kazanmış____ sevindi.", options: ["çasına", "arak", "dığı için", "meden"], correct: 0 },
  { q: "Gerek öğrenciler,____ öğretmenler bu karardan memnun kaldı.", options: ["gerekse", "hem de", "ne de", "rağmen"], correct: 0 },
  { q: "Bu işi bitirmek____ başka çaresi yoktu.", options: ["ten", "e", "de", "le"], correct: 0 },
  { q: "Zaman geçtik____, her şeyi daha iyi anladım.", options: ["çe", "en", "ten sonra", "meden"], correct: 0 },
  { q: "Biz burada, tren gel____ bekleyeceğiz.", options: ["ene kadar", "diğinde", "meden", "erek"], correct: 0 },
  { q: "Sözleşme, her iki taraf da imzala____ şartıyla geçerli olacak.", options: ["ması", "dığı", "acağı", "arak"], correct: 0 },
  { q: "Trafik yüzünden, toplantıya geç kal____ zorunda kaldım.", options: ["mak", "dım", "acağım", "ıyorum"], correct: 0 },
  { q: "O, her zaman söyle____ gibi, sözünde durdu.", options: ["diği", "yeceği", "mesi", "erek"], correct: 0 },
  { q: "Bu karar, üst yönetim tarafından____.", options: ["alındı", "aldı", "alıyor", "alacak"], correct: 0 },
  { q: "O, işe başladığından____ hiç izin almadı.", options: ["beri", "sonra", "önce", "dolayı"], correct: 0 },
  { q: "Sanki bu şehri hiç tanımıyor____ sorular soruyordu.", options: ["muş gibi", "masına rağmen", "dığı için", "arak"], correct: 0 },
  { q: "Bu sorunu çözme____ sürece, ilerleyemeyiz.", options: ["diğimiz", "yeceğimiz", "mesi", "erek"], correct: 0 },
  { q: "Onun başarılı olacağına____ hiç şüphem yok.", options: ["dair", "rağmen", "göre", "kadar"], correct: 0 },
  { q: "Bu konuda hiç kimse ondan daha____ değil.", options: ["bilgili", "bilgi", "bilgilenmiş", "bilgiyle"], correct: 0 },
  { q: "Şirket, maliyetleri azaltmak____ birçok çalışanı işten çıkardı.", options: ["suretiyle", "rağmen", "göre", "kadar"], correct: 0 },
  { q: "Sen bana yardım et____, bu işi asla bitiremezdim.", options: ["meseydin", "tiğin için", "erek", "meden"], correct: 0 },
];

module.exports = { A1, A2, B1, B2 };